### ISSUE TITLE
Vnmrbg could not be started on Ubuntu 16.04 on Oracle VirtualBox

### ISSUE THREAD

**Issue by Kas-scientist** [OpenVnmrJ/OpenVnmrJ#149]
Hello,
first of all I want to thank you for all the work that all of you have done to make this running.

I had Open VnmrJ on a laptop half a year ago, working without problems in Ubuntu 16.04 (not in a Virtual machine) but now I have a new laptop and I don't want to install Ubuntu in a dedicated partition, I want to run it in a Virtual Machine.

I had instaled 2 times Ubuntu 16.04 and VnmrJ (dvdimageOVJMI_REL_TEST9) on the Oracle VirtualBox but I have this error when I start vnmrj.
![1](https://user-images.githubusercontent.com/37886456/38063042-713c5e9e-32f7-11e8-93b6-32f20b975e9d.JPG)

My hostname is on etc/hosts file
![2](https://user-images.githubusercontent.com/37886456/38063067-8186afe8-32f7-11e8-8a72-410e7cf01921.JPG)
![3](https://user-images.githubusercontent.com/37886456/38063070-83121ab4-32f7-11e8-9767-4eb3ccf05f46.JPG)

So I don't know what might be happening and how can I solve this error.

Thanks.

**Comment by DanIverson** [comment]
Could you edit the /etc/hosts file. Delete the line with
 127.0.1.1  kas
and add kas to the line with localhost so it reads
  127.0.0.1    localhost  kas

**Comment by Kas-scientist** [comment]
Still the same error.

I have restarted the VirtualBox after changing etc/hosts because I want to be sure that Ubuntu reads the changes in the file.

![4](https://user-images.githubusercontent.com/37886456/38063388-2fd2ab8c-32f9-11e8-9368-69ab806927e2.JPG)

**Comment by DanIverson** [comment]
Does "ping kas" work?  Also, what does "ldd /vnmr/bin/Vnmrbg" display?

**Comment by Kas-scientist** [comment]
"ping kas" work
![5](https://user-images.githubusercontent.com/37886456/38064493-81251c40-32fe-11e8-9b04-f7877096217f.JPG)

and "ldd /vnmr/bin/Vnmrbg" says "it's not a dinamic executable" in Spanish (my system language)
![6](https://user-images.githubusercontent.com/37886456/38064515-9cfe891a-32fe-11e8-9393-0e296ea1e9e3.JPG)

**Comment by Kas-scientist** [comment]
I'm searching even more using your tips as orientation.
I have instaled gcc-multilib with the usual "sudo apt-get install gcc-multilib" and now "ldd /vnmr/bin/Vnmrbg" says:
![7](https://user-images.githubusercontent.com/37886456/38064716-e22bf72e-32ff-11e8-8ca2-72158142068e.JPG)

**Comment by Kas-scientist** [comment]
![8](https://user-images.githubusercontent.com/37886456/38064991-3ea0a8b4-3301-11e8-822b-6a7750759eaa.JPG)
And it seems that with that it works now, thanks.

The solution was installing "gcc-multilib", I find it strange because I think that I had instaled the 32 libraries before installing open VnmrJ, but anyway, that solves the problem.

Thanks.

**Comment by Kas-scientist** [comment]
Hmm... it's still giving some errors and I can't see the experiment selector tree and fids can't load :(

![9](https://user-images.githubusercontent.com/37886456/38065429-a6f8460e-3303-11e8-89d7-272973dbd684.JPG)

**Comment by DanIverson** [comment]
It looks like progress. The errors in your last post are because OVJ is in Exp: 0, as seen in the blue line just below the command line. Enter the following into the OVJ command line and things should look better.
    jexp1   rt('/vnmr/fidlib/fid1d') wft

**Comment by Kas-scientist** [comment]
![aaa](https://user-images.githubusercontent.com/37886456/38093165-6f5786bc-336a-11e8-810d-145b335c837d.JPG)
It works now and I can see experiments on it, thanks.
