### ISSUE TITLE
vjqa creates two log files when run across midnight

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/OpenVnmrJ#203]
I propose changing the output file name to 'report.txt' or 'report.log' rather than YYYY-MM-DD, this will allow external programs to reliably find the report file.  Another option would be for 'vjqa' to take an argument for 'output file name'.  Thoughts?

It happened here (see the Artifacts tab and results of the last stage "Store VJQA Results"):
https://circleci.com/gh/tesch1/OpenVnmrJ/176

**Comment by DanIverson** [comment]
I added a PR #204 but have not tested it. It maintains a single logfile if run past midnight (change in vvLog macro). It also makes a link to the current log file with a standard name (report.txt in vjqa macro). I like to maintain the dated log files since I don't always look at them every day. With a history, I can pinpoint the day something started to fail. If you can test the PR and it works, I will merge it.

**Comment by tesch1** [comment]
Build/test is running here:  https://circleci.com/gh/tesch1/OpenVnmrJ/177

While we're at it, could we add HH:MM to the filename too?

Did you ever get the credentials for the OpenVnmrJ github project?  Since CircleCI is setup and building and running tests, we could enable it to run on PRs for the main repo too.  It's free for open source projects up to some number of build hours per month.

**Comment by DanIverson** [comment]
Added hour and minute to file name.
Have not yet signed up for travis-ci or circleCI. It is on my list of things to do.

**Comment by tesch1** [comment]
I currently prefer CircleCI, it has nice features and a snappy interface.  I think you can sign up for it directly through the OpenVnmrJ github account: https://circleci.com/signup/.  I haven't gotten vjqa running on travis - didn't seem necessary.  I'm thinking about removing the travis stuff entirely, CircleCI feels like the winner for now.

**Comment by tesch1** [comment]
meh, had to rebase on to the latest master, and run again because the 'vjqa' branch was missing changes from a recent PR that fixed how the reports were stored by circleci.  running again...

https://circleci.com/gh/tesch1/OpenVnmrJ/180

**Comment by tesch1** [comment]
Oh, except I forgot one good thing about travis -- they have a free macos build environment for open source.  CircleCI apparently will offer it too, but their website says you need to request it - https://circleci.com/pricing/#faq-section-linux says "We also offer the Seed plan free (at 1x concurrency) for OS X open source projects. Contact us at billing@circleci.com for access. If you are building a bigger open-source project and need more resources, let us know how we can help you!"

**Comment by tesch1** [comment]
This is fixed, afaict.
