### ISSUE TITLE
Support or at least detect Java9/10 on macos, and/or fail deterministically

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/OpenVnmrJ#208]
Running on Mac uses the system java - if the user has java 10 installed, startup hangs without any useful message to the user.

**Comment by tesch1** [comment]
From this thread on spinsights: https://spinsights.chem.agilent.com/message/20671

**Comment by DanIverson** [comment]
I have been looking for a robust way to get the java version in a bash script. This seems to work:
vers=$(java -fullversion 2>&1 | awk 'BEGIN {FS="\""} {print $2}' | awk 'BEGIN {FS="."} {print $1}')

**Comment by DanIverson** [comment]
Should be fixed with PR #241

**Comment by tesch1** [comment]
should the second one be `print $2`?

**Comment by DanIverson** [comment]
No, it is the first number. They changed the java version scheme. Up until java 8, it was 1.6.x, 1.7.x, and 1.8.x. With java 9 and 10, it is now 9.x.y and 10.x.y. I just get the first number and test whether it is greater than 8.

**Comment by tesch1** [comment]
Ah yes, what good is a scheme if you dont change it once in a while :)  I suppose I'll close this too.
