### ISSUE TITLE
how to install teh soft?

### ISSUE THREAD

**Issue by uebmaster** [OpenVnmrJ/OpenVnmrJ#209]
i have doubts about the installation process.

Actually the computer where i have the varian soft has failed, and i must to use a different computer and i am having troubles to make a new install.

Searching i found this soft that i understand could remplace the original soft, but i read this: "OpenVnmrJ does not contain console software"

What means?

I am newbie in the topic but we need that the computer works, someone could help me?

Thanks in advance.

**Comment by DanIverson** [comment]
The comment that "OpenVnmrJ does not contain console software" means that if you want to connect your new computer to a Varian/Agilent spectrometer, you first need to install VnmrJ 4.2 and the "110" patch. After that, you can install OpenVnmrJ. If your new computer is only going to be used for data processing, then you do not need to install VnmrJ 4.2 first.

**Comment by uebmaster** [comment]
where can i download VnmrJ 4.2? we just have Vnmrj 3.2 Linux Version.

**Comment by DanIverson** [comment]
If you are on SpinSights, all of the information is here ( https://spinsights.chem.agilent.com/docs/DOC-12723 ). Basically, you need to order it from your Agilent service person.

**Comment by uebmaster** [comment]
ok, thanks.

**Comment by DanIverson** [comment]
With the release of OpenVnmrJ Version 2.1, one no longer needs to first install VnmrJ 4.2 and the 110 patch. OpenVnmrJ Version 2.1 includes the console software. Also, there are installation instructions at https://github.com/OpenVnmrJ/OpenVnmrJ/blob/master/Install.md
