### ISSUE TITLE
Proton spectrum failed during acquire

### ISSUE THREAD

**Issue by timburrow** [OpenVnmrJ/OpenVnmrJ#21]
David Rice reports:
I just loaded OVJ8.1 on our Propulse 500 and ran into a  
problem.  I’ve set the machine back to 4.2 and there is no 
problem – so there must be a bug. 

Note that I am running on RHEL6.3.  The OVJ installation worked 
fine.  I did run setacq.   

My first test spectrum was a PROTON protocol of the lineshape 
sample.  We have a 96-sample robot.  The sample should have 
loaded – done some 2H gradient auto shimming, auto locked, run 4scans 
and then be returned. I found that the run completed and saved the data 
but then hung before being returned.  The next few lines are an (approximation to the) error 
message that appeared around that time in the terminal with su acqproc. 
I am not precisely sure it was related though. 
```
src/nrecvproc/fidObj line 175 fOpen posix_fallocate(1,2,0,0) of (null) failed /fid 
no message of the desired type  ‘src/nrecvproc/recvfuncs.c line 379 recvData could not  Open Fid. 
```
The sample was not returned.  

I repeated this three times after resetting with su acqproc and restarting automation.

**Comment by DanIverson** [comment]
This should be fixed by pull request #25
