### ISSUE TITLE
How can I run OpenVnmrJ on Windows 10?

### ISSUE THREAD

**Issue by gilsonjunior23** [OpenVnmrJ/OpenVnmrJ#269]
What's on your mind?

**Comment by DanIverson** [comment]
Currently, the only way is to install something like VirtualBox or VMWare with the guest OS as some variant of Linux (CentOS, Ubuntu, etc).

**Comment by kloudpaper** [comment]
You can refer to this thread too: [](https://github.com/OpenVnmrJ/OpenVnmrJ/issues/271)
