### ISSUE TITLE
circleci

### ISSUE THREAD

**Issue by DanIverson** [OpenVnmrJ/OpenVnmrJ#280]
circleci build is failing.
Apparently, the circleci environment does not have 64-bit versions of motif and Xt. When I converted pulsetool to use 64-bit motif, the circleci build breaks.

**Comment by DanIverson** [comment]
circleci should no longer need the 32-bit motif package

**Comment by tesch1** [comment]
Yeah, I saw that too but didn't have time to investigate.

Did you ever get the OpenVnmrJ github password?  would be nice to enable circleci builds on all PRs (or just the master branch so it builds after a PR is merged?).  Right now they only build when I get around to updating my master branch, which maybe isnt the best feedback loop.
