### ISSUE TITLE
OpenVNMRJ on CentOS 7?

### ISSUE THREAD

**Issue by DavidGeeraerts** [OpenVnmrJ/OpenVnmrJ#287]
Is it possible to get OpenVNMRJ (Mercury console distribution) to work with CentOS 7?
If I understand the documentation correctly for OpenVNMRJ, VNMRJ 4.2 needs to be already installed (?).
Where could I get VNMRJ 4.2 if I don't have it?
We have an old Varian\Agilent AS400 NMR, currently running on RHEL 5.x with VNMRJ 2.2D.
Our goal is to replace the computer, running CentOS 7 ideally, and if possible, OpenVNMRJ.

Thank you for your time.
David Geeraerts
Scientific Computing Manager | Evergreen State College

**Comment by DanIverson** [comment]
Yes, it is possible. I have it working with CentOS 7.4, 7.5, and 7.6. I have not yet committed the required changes to github. I want to do a little beta testing first. I think it will be ready in a month or so. Version 1 of OpenVnmrJ does require that VnmrJ 4.2 and the 110 patch are installed. With this new Version 2, that will not be required.

**Comment by DavidGeeraerts** [comment]
That is great news on all fronts! So with OpenVnmrJ v2.0, it will be a stand-alone installer, not requiring any previous VnmrJ installations (?).
We here in the Sciences are grateful for the work you do to continue support for older NMR's.

**Comment by DanIverson** [comment]
OpenVnmrJ Version 2 is now released and it supports CentOS 7. It does not require any previous VnmrJ installation.
