### ISSUE TITLE
warnings from scons

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/OpenVnmrJ#38]
scons: warning: The env.Copy() method is deprecated; use the env.Clone() method instead.File "/Users/travis/build/tesch1/OpenVnmrJ/src/3D/SConstruct", line 73, in <module>

scons: warning: The Options class is deprecated; use the Variables class instead.
File "/Users/travis/build/tesch1/OpenVnmrJ/src/biopack/../../scripts/buildoptions.py", line 23, in <module>

**Comment by DanIverson** [comment]
These are fixed with PR #356
