### ISSUE TITLE
Vnmrbg could not be started

### ISSUE THREAD

**Issue by ruetherm** [OpenVnmrJ/OpenVnmrJ#400]
**Describe the bug**
Installation of OpenVnmrJ on Centos 8.2 worked fine. If main program is started an error message "Vnmrbg could not be started" is shown. Clicking on "OK" will close the program. Other GUI start and work normally i.e OpenVnmrJ Administrtor, Accountant. Only the main program currently give this error message.

**To Reproduce**
This error occurs always when starting OpenVnmrJ

**Expected behavior**
To open and run OpenVnmrJ normally

**Version of OpenVnmrJ you are using.**
- Using newest version 2,1
- Downloaded from GitHub 
- Followed installation instruction. Installation was performed with "noPing" as our institution does not support "ping" to the outside world

**Messages and Logs**
## DEBUG Aug 7, 2020 10:25:04 DB version: pg_ctl (PostgreSQL) 7.4.5  DB Host: spinecho-chy-tcd-ie
              Local Host: spinecho-chy-tcd-ie     Network Mode: false
## DEBUG Aug 7, 2020 10:29:45 Calibration  Experiment Selector

**Environment (please complete the following information):**
 - OS: Centos 8.2

**Additional context**
Other GUI start and work normally i.e OpenVnmrJ Administrtor, Accountant. Only the main program currently give this error message. OpenVnmrJ is not connected to a spectrometer.

**Comment by DanIverson** [comment]
Did you try running the ovjDiag script? It might give us a clue. The normal cause is network configuration. What do you get from running the following from a terminal:
   hostname
   ping `hostname`

**Comment by ruetherm** [comment]
Hi Dan,

yes I tried pinging the host and that is not a problem. I also have internet access.

Running the script ovjDiag does not show anything. It just says "completed". Is there a log file saved somewhere when running the script?

**Comment by DanIverson** [comment]
There is no log file for the ovjDiag script. Could you send me the ~/vnmrsys/VnmrjMsgLog file? What do you get when you run the following from a terminal window:
  Vnmrbg -mback -n1 dg

**Comment by ruetherm** [comment]
[VnmrjMsgLog.zip](https://github.com/OpenVnmrJ/OpenVnmrJ/files/5049705/VnmrjMsgLog.zip)

I attached the VnmrjMsgLog file

The output for Vnmrbg -mback -n1 dg is:
[vnmr1@spinecho Desktop]$ Vnmrbg -mback -n1 dg
Exp:1   
Index: 1   
           
Seq: PROTON
Exp:1   
Index: 1   
           
   ACQUISITION         TRANSMITTER           SPECIAL            PROCESSING
seqfil       s2pul  tn              H1  temp          25.0  lb            0.30
sw          8012.8  sfrq       499.838  spin             0  sb        not used
at           2.045  tof          499.7  gain            34  gf        not used
np           32768  tpwr            58  hst          0.008  awc       not used
fb            4000  pw           4.900  pw90         9.800  lsfid     not used
bs              32      DECOUPLER       alfa        10.000  fn          262144
ss               2  dn             C13    PRESATURATION           FLAGS
d1           1.000  dof              0  satmode          n  il               n
nt               8  dm             nnn  wet              n  in               n
ct               8  decwave W40_HCN5mm   Details in dgss    dp               y
      SAMPLE        dpwr            40                      hs              nn
date   Mar 30 2014  dmf          32258
solvent      cdcl3
sample Ethylindano~
                ne
SVPAR   
SAVEDATA

**Comment by ruetherm** [comment]
Hi Dan,

problem is solved. The hostname was not in the .etc/host file. That caused the problem. The program seems to work now.

Thank you for all your help,
Regards,
Manuel
