### ISSUE TITLE
verifyControllers 

### ISSUE THREAD

**Issue by ronkerkhof** [OpenVnmrJ/OpenVnmrJ#513]
Hello,
When installing CentOS 7 I am able to run the verifyController.py,
CentOS 8 is not working as it is using Python version 3
Is there a workaround with CentOS 8
Ron Kerkhof

**Comment by DanIverson** [comment]
These were fixed last month but have not yet been included in a release. You can get the three files with the commands

https://raw.githubusercontent.com/OpenVnmrJ/OpenVnmrJ/master/src/ddr/adm/acq/verifyCntlrsFlash
https://raw.githubusercontent.com/OpenVnmrJ/OpenVnmrJ/master/src/ddr/adm/acq/verifyCntlrsFlash.py
https://raw.githubusercontent.com/OpenVnmrJ/OpenVnmrJ/master/src/ddr/adm/acq/verifyCntlrsFlash3.py

Copy them to /vnmr/adm/acq and then run
   /vnmr/adm/acq/verifyCntlrsFlash
