### ISSUE TITLE
detect if VnmrJ4.2 is running and offer to switch automatically

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/OpenVnmrJ#54]
apropos https://spinsights.chem.agilent.com/docs/DOC-12771

**Comment by timburrow** [comment]
💯 
The script is Apache licensed now, so it can be included and used in the install script.

It'll be part of the openvnmrj-utils appdir

**Comment by tesch1** [comment]
Ah, cool!

(somewhat off topic..)
I'm a little confused as to what all the git repos are supposed to do?

It's the first project I've seen that's organized this way, so it's taking me a bit to wrap my head around....

Am I understanding right that this the intended directory layout:

ovjbuild/
ovjbuild/ovjTools
ovjbuild/OpenVnmrJ
ovjbuild/(other buid staging directories)
ovjbuild/appdirs...

with environment variables:
ovjBuildDir=../path/to/ovjbuild
OVJ_TOOLS=$ovjBuildDir/ovjTools

?

**Comment by tesch1** [comment]
covered by #18
