### ISSUE TITLE
#! lines need updated for expect scripts

### ISSUE THREAD

**Issue by JessiBaughman** [OpenVnmrJ/OpenVnmrJ#588]
**Describe the bug**
The expect scripts /vnmr/bin/loginpassword and /vnmr/bin/loginpasswordcheck fail to run if called directly.

**To Reproduce**
Steps to reproduce the behavior (e.g. loginpasswordcheck):
1. run `/vnmr/bin/loginpasswordcheck username password`
2. (t)csh returns > "argc: Undefined variable."
3. bash returns > " ./loginpasswordcheck: line 20: syntax error near unexpected token `}' 
                    ./loginpasswordcheck: line 20: `} elseif {$argc == 1} {' "

**Expected behavior**
loginpasswordcheck: return "Invalid password" or "Password correct"

**Version of OpenVnmrJ you are using.**
VnmrJ 4.2A_110 and OVJ August 2, 2021 build

**Environment (please complete the following information):**
 - OS: CentOS 6.10 and RHEL 8.4

**Workaround (or perhaps intended use)**
Call the scripts with "expect -f". (e.g. `expect -f /vnmr/bin/loginpasswordcheck username password`)

**Fix**
Move the #! line to line 1 and change it from `#!/bin/sh` to:
`#! /usr/bin/expect -f`
Then the scripts will execute regardless if called directly or with "expect -f". #! needs to be line 1 for this to work.

**Comment by DanIverson** [comment]
Thanks Jessi. Just implemented your fix
