### ISSUE TITLE
Support Interix?

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/OpenVnmrJ#69]
It no longer exists for windows 10: https://en.wikipedia.org/wiki/Interix

Any reason to keep it around?  Is anyone still using it?

**Comment by DanIverson** [comment]
There may be VJ users that still run Interix but I don't think we need to worry about it for OVJ users. I left it in just to avoid making any mistakes while removing it. I did not have a lot of time to re-test things. A Windows 10 development that would be interesting to investigate is if OVJ will run in their implementation of the bash / ubuntu shell: https://msdn.microsoft.com/en-us/commandline/wsl/about
