### ISSUE TITLE
inetd / xinetd / systemd.  ubuntu installs openbsd-inetd by default

### ISSUE THREAD

**Issue by tesch1** [OpenVnmrJ/OpenVnmrJ#77]
At least we should support both inetd and xinetd, so as not to force users into one.  In the future might make sense to support systemd (although low priority, since systemd is currently compatible with inetd/xinetd  (I think)).

Propose:
Immediate fix: add xinetd to ubuntu/debian required packages list, forcing users to switch from openbsd-inetd.
Future: support both inetd/xinetd
Future of future: support systemd

**Comment by DanIverson** [comment]
I think this is resolved. Current Ubuntu versions use systemd. Reopen if still an issue.
