### ISSUE TITLE
dicom files are empty  in the output dicom directory in openvnmrj 3.1

### ISSUE THREAD

**Issue by mosquitozheng** [OpenVnmrJ/OpenVnmrJ#772]
Openvnmrj 3.1 cannot properly convert FDF images to Dicom. The output directory are all empty with nothing (no Dicom files created). This function was working well in the Agilent Vnmrj. The binary file for this conversion is FdfToDcm. Don't know how to solve this bug

**To Reproduce**
1. Go to 'I/O' -->'Format Conversion'-->choose "format: DICOM"--> chose a loaded image
2. Click on 'Save'
3. It would show: "save ......Done", but not files in the output folder created.

**Comment by DanIverson** [comment]
The attached zip file contains an aipOut script that corrects the grep error. Unzip the attachment and then
  mv aipOut /vnmr/bin/.
Does this correct the DICOM conversion?
[fix.zip](https://github.com/OpenVnmrJ/OpenVnmrJ/files/11490735/fix.zip)

**Comment by mosquitozheng** [comment]
> The attached zip file contains an aipOut script that corrects the grep error. Unzip the attachment and then mv aipOut /vnmr/bin/. Does this correct the DICOM conversion? [fix.zip](https://github.com/OpenVnmrJ/OpenVnmrJ/files/11490735/fix.zip)

Comment: I did remove the above "grep ....." error. But the output dicom folder is still empty.

**Comment by mosquitozheng** [comment]
![image](https://github.com/OpenVnmrJ/OpenVnmrJ/assets/133734701/92504d6b-c0cb-4961-a2c0-c37d54db705a)

Comment：remove the above 'grep -o...' in two places of aipOut, it will generate the dicom files.
![image](https://github.com/OpenVnmrJ/OpenVnmrJ/assets/133734701/541ba9dc-ff94-4573-9f46-ce8c5b4530b1)

**Comment by mosquitozheng** [comment]
If I remove the "grep ....' in the aipOut, openvnmrj can convert individual image folder to dicom. However, if I choose a whole study (which has several folders of img FDFs from different sequences, it does nothing. It works well under redhat 6.3, but not on  openvnmrj under centos 7. please refer to below pictures.
![image](https://github.com/OpenVnmrJ/OpenVnmrJ/assets/133734701/33219540-8eaf-46cd-9645-24027ad20929)
![image](https://github.com/OpenVnmrJ/OpenVnmrJ/assets/133734701/942c4c87-d465-46b1-9f9e-07fc6f536b2e)
