### ISSUE TITLE
blank page on the Colormap panel in OpenVnmrj imaging interface

### ISSUE THREAD

**Issue by mosquitozheng** [OpenVnmrJ/OpenVnmrJ#774]
a bug as shown below:

/home/vnmr1/imaging/template/layout/toolpanels/aipcolormap.xml

![image](https://github.com/OpenVnmrJ/OpenVnmrJ/assets/133734701/39832915-c55c-4256-9181-f98555aa0834)

**Comment by mosquitozheng** [comment]
Notice there are some differences on the Locator. Those items related to Imaging are all missing. Is this the reason why aipColormap.xml cannot be shown on the toolPanel???

![image](https://github.com/OpenVnmrJ/OpenVnmrJ/assets/133734701/2f940614-bbf8-40ce-9940-f5edbfde27f8)

**Comment by DanIverson** [comment]
Fixed by PR #775. The missing items in the Locator were fixed by updating the Locator.
