### ISSUE TITLE
Displaying arrayed data in a stack (v/h) not always working

### ISSUE THREAD

**Issue by Bkaribo** [OpenVnmrJ/OpenVnmrJ#807]
When an arrayed experiment is plotted with e.g. dssh OVJ writes the error
"Array delta > start - stop!"

and then only the first spectrum of the array is shown (the rest of the display screen for spectra stays white).
In the procpar file the arraystart/arraydelta/arraystop parameters are 1/1/1 which explains the error. The Arrayed data is found under the parameter (e.g.) 'd2' with the corresponding arrayed values.

**Expected behavior**
arraystart/arraystop/arraydelta should be set correctly, or if not possible (non uniform data) the array should still be displayed stacked

**Version of OpenVnmrJ you are using.**
current master
OVJ_B12 install

**Environment (please complete the following information):**
Ubuntu 20.04

**Additional context**
This error is hard to reproduce, sometimes it doesn't appear for an experiment type, but repeating the acquisition produces the ''wrong' metadata that are saved. The error seems to appear when arraying data with manual non-uniform values (e.g. : d2 -> d2=0,0.1,0.2,0.5,1) but it has been observed to appear with uniform spaced points.

*Log file/Error msg*

will be added later

typical procpars for the array (non - uniform array values):
```
arraydim 7 1 32768 1 1 2 1 5 1 64
1 25 
0 
array 2 2 256 0 0 2 1 1 1 64
1 "d2"
0 
arraydelta 7 1 32767 0 0 4 1 0 1 64
1 1 
0 
arraymax 7 1 32767 0 0 4 1 0 1 64
1 25 
0 
arrayflip 4 2 4 0 0 4 1 0 1 64
1 "n"
0 
arrayelemts 1 1 9.99999984307e+17 -9.99999984307e+17 0 2 1 0 1 64
1 1 
0 
arraystop 7 1 32767 0 0 4 1 0 1 64
1 1 
0 
arraystart 7 1 32767 0 0 4 1 0 1 64
1 1 
0 
```

**Comment by DanIverson** [comment]
From OVJ, could you run 
jFunc(55,'/vnmr/tmp/arrayBug')
debug('c3')
When you next get the error, run
 debug('C')
and send me the /vnmr/tmp/arrayBug file
