### ISSUE TITLE
This code looks leftover from a debugging session

### ISSUE THREAD

**Issue by bdezonia** [OpenVnmrJ/OpenVnmrJ#843]
See this line of code:

https://github.com/OpenVnmrJ/OpenVnmrJ/blob/0ad7471b90726f53a32eef7d3aa53085f84d9bf1/src/nvpsg/solidmpseqs.h#L461

See that it is setting n90m etc to hard coded values. Look a few lines above and notice that they were already set in a standard way.

Is the existing code leftover from a debugging session?

**Comment by DanIverson** [comment]
This code is in a function that is never used.
