### ISSUE TITLE
Is this a fencepost error?

### ISSUE THREAD

**Issue by bdezonia** [OpenVnmrJ/OpenVnmrJ#848]
See this line of code:

https://github.com/OpenVnmrJ/OpenVnmrJ/blob/0ad7471b90726f53a32eef7d3aa53085f84d9bf1/src/nvpsg/solidmpseqs.h#L5505

Should the if test be stated as "<= 0" instead of as "< 0"? The error message implies 0 might be a bad value but our current code is not catching it.

**Comment by DanIverson** [comment]
It looks like it should be <= 0. If you make the change, you might also change the two lines
   print(...);
   psg_abort(1);
to
   abort_message(...);
like you did in soldhhdec.h
